server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: EMPLEADO-SERVICE
        uri: lb://EMPLEADO-SERVICE
        predicates:
          - Path=/api/empleado/**
          

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
      hostname: localhost